server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
  
    name: cocktails
  
  datasource:
   url: jdbc:mysql://database-1.cls4oq20gmca.ap-northeast-2.rds.amazonaws.com:3306/MonsterDB
   username: admin
   password: admin1013
   driver-class-name: com.mysql.cj.jdbc.Driver
   
  jpa:
   show-sql: true
   properties:
    hibernate:
      format_sql: true
      show_sql: true
   hibernate:
    ddl-auto: create
  profiles:
    include: oauth
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: HXj22oVU2540zif4gFmn
            client-secret: 5D4Hsx313A
            scope: [name, email]
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: 'https://localhost:9092/login/auth/naver/callback'
          kakao:
            client-id: ff186d351034c6d3db268df03e7c596a
            client-secret: 6bX9xJgRVwbFUApqPU0fi3nEiWjNY4Cd
            scope: [openid, profile, account_email, profile_nickname]
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: 'https://localhost:9092/login/auth/kakao/callback'
            client-authentication-method: client_secret_post
          google:
            client-id: 589056962488-5211p8t3nk7etdiajjp3qdgg7n4jdi4e.apps.googleusercontent.com
            client-secret: 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
            scope: [email, profile, openid]
            client-name: Google
            authorization-grant-type: authorization_code
            redirect-uri: 'https://localhost:9092/login/auth/google/callback'
        provider:
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            user-name-attribute: response
          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: "https://kauth.kakao.com/oauth/token"
            user-info-uri: "https://kapi.kakao.com/v2/user/me"
            user-name-attribute: id
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/v2/auth"
            token-uri: "https://oauth2.googleapis.com/token"
            user-info-uri: "https://openidconnect.googleapis.com/v1/userinfo"
            user-name-attribute: sub
  config:
    import:
      - classpath:/yaml/application-{verification}.yml
      - classpath:/yaml/application-{weather}.yml
      

logging:
  level:
    org:
      springframework:
        security: TRACE
        security.oauth2: TRACE
      hibernate:
        SQL: debug
        type: trace

jwt:
  secret-key: "J6Dfye3LvLpH2EM5B6W9XSn7HURx5Vhsw7pqG9T6moE="

rapid:
  api:
    requestURI: "https://the-cocktail-db.p.rapidapi.com/filter.php?i=Gin"
    host: "the-cocktail-db.p.rapidapi.com"
    key: "994a06b8f2mshbff0e95525f145fp1f054bjsn7eefc7c1bcf9"
